# @package _global_

defaults:
  - motion_tracking

# Env structure
env:
  _target_: humanoidverse.envs.motion_tracking.amp_motion_tracking.AMPMotionTracking
  config:
    # 继承motion tracking的所有配置
    amp_reward_weight: 0.5
    
    # AMP数据处理配置
    amp_data_config:
      sample_dt_multiplier: 2  # 每2个时间步采样一次
      min_motion_length: 1.0   # 最小动作长度（秒）
      max_motions_to_load: 100 # 最大加载的motion数量
      include_body_positions: False  # 是否包含身体位置特征
      normalize_observations: True   # 是否标准化观测

# Globally accessible parameters
log_task_name: amp_motion_tracking

eval_overrides:
  env:
    config: 
      max_episode_length_s: 100000
