# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 31
  dof_obs_size: 30
  actions_dim: 30
  lower_body_actions_dim: 12 # Yuanhang
  upper_body_actions_dim: 15 # Yuanhang
  policy_obs_dim: -1 # Jiawei
  critic_obs_dim: -1
  # policy_obs_dim: 45 # Jiawei
  # critic_obs_dim: 238
  # policy_obs_dim: 45 # Jiawei
  # policy_obs_dim: 241 # Jiawei
  # self_obs_max_coords: 298  # ${eval:1+20*(3+6+3+3)-3}

  key_bodies: ["L_ANKLE_R_S", "R_ANKLE_R_S"]
  contact_bodies: [ "L_ANKLE_R_S", "R_ANKLE_R_S" ]
  num_feet: 2
  right_foot_name: "R_ANKLE_R_S"
  left_foot_name: "L_ANKLE_R_S"
  foot_name: "ANKLE_R_S"
  knee_name: "KNEE_P_S"
  has_torso: True
  torso_name: "WAIST_P_S"
  has_upper_body_dof: True
  dof_names: ['L_HIP_P', 'L_HIP_R', 'L_HIP_Y', 'L_KNEE_P', 'L_ANKLE_P', 'L_ANKLE_R', 'R_HIP_P', 'R_HIP_R', 'R_HIP_Y', 'R_KNEE_P', 'R_ANKLE_P', 'R_ANKLE_R', 
                'WAIST_Y', 'WAIST_R', 'WAIST_P', 'L_SHOULDER_P', 'L_SHOULDER_R', 'L_SHOULDER_Y', 'L_ELBOW_Y', 'L_WRIST_P', 'L_WRIST_Y', 
                'L_WRIST_R', 'NECK_Y', 'R_SHOULDER_P', 'R_SHOULDER_R', 'R_SHOULDER_Y', 'R_ELBOW_Y', 'R_WRIST_P', 'R_WRIST_Y', 'R_WRIST_R']
  upper_dof_names: [ 'L_SHOULDER_P', 'L_SHOULDER_R', 'L_SHOULDER_Y', 'L_ELBOW_Y', 'L_WRIST_P', 'L_WRIST_Y', 'L_WRIST_R', 'NECK_Y',
                     'R_SHOULDER_P', 'R_SHOULDER_R', 'R_SHOULDER_Y', 'R_ELBOW_Y', 'R_WRIST_P', 'R_WRIST_Y', 'R_WRIST_R']
  upper_left_arm_dof_names: ['L_SHOULDER_P', 'L_SHOULDER_R', 'L_SHOULDER_Y', 'L_ELBOW_Y', 'L_WRIST_P', 'L_WRIST_Y', 'L_WRIST_R']
  upper_right_arm_dof_names: ['R_SHOULDER_P', 'R_SHOULDER_R', 'R_SHOULDER_Y', 'R_ELBOW_Y', 'R_WRIST_P', 'R_WRIST_Y', 'R_WRIST_R']
  lower_dof_names: ['L_HIP_P', 'L_HIP_R', 'L_HIP_Y', 'L_KNEE_P', 'L_ANKLE_P', 'L_ANKLE_R', 'R_HIP_P', 'R_HIP_R', 'R_HIP_Y', 'R_KNEE_P', 'R_ANKLE_P', 'R_ANKLE_R',
                    'WAIST_Y', 'WAIST_R', 'WAIST_P']
  waist_dof_names: ['WAIST_Y', 'WAIST_R', 'WAIST_P']
  dof_pos_lower_limit_list: [-3.1400, -0.2610, -3.1400, -0.8300, -1.5700, -0.6400, -3.1400, -1.7440,
                              -3.1400, -2.3000, -0.6140, -0.6400, -3.1400, -0.6100, -0.2440, -3.1400,
                              -1.5700, -3.1400, -2.4000, -3.1400, -0.6900, -2.3500, -3.1400, -3.1400,
                              -1.5700, -3.1400, -0.8700, -3.1400, -0.6900, -0.3480]
  dof_pos_upper_limit_list: [3.1400, 1.7440, 3.1400, 2.3000, 0.6140, 0.6400, 3.1400, 0.2610, 3.1400,
                              0.8300, 1.5700, 0.6400, 3.1400, 0.6100, 0.5230, 3.1400, 1.5700, 3.1400,
                              0.8700, 3.1400, 0.6900, 0.3480, 3.1400, 3.1400, 1.5700, 3.1400, 2.4000,
                              3.1400, 0.6900, 2.3500]
  dof_vel_limit_list: [ 5.7600,  8.0600,  6.8100,  5.7600,  8.0600, 10.1600,  5.7600,  8.0600,
                        6.8100,  5.7600,  8.0600, 10.1600,  8.0600,  8.0600,  8.0600,  8.0600,
                        8.0600,  8.5900,  8.5900, 10.1600, 12.3600, 12.3600, 12.3600,  8.0600,
                        8.0600,  8.5900,  8.5900, 10.1600, 12.3600, 12.3600]
  dof_effort_limit_list: [267.0000,  69.0000, 121.0000, 267.0000,  69.0000,  23.0000, 267.0000,
                          69.0000, 121.0000, 267.0000,  69.0000,  23.0000,  63.0000,  63.0000,
                          63.0000,  63.0000,  63.0000,  42.0000,  42.0000,  23.0000,   8.3000,
                            8.3000,   8.3000,  63.0000,  63.0000,  42.0000,  42.0000,  23.0000,
                            8.3000,   8.3000]
  


  body_names: ['base_link', 'L_HIP_P_S', 'L_HIP_R_S', 'L_HIP_Y_S', 'L_KNEE_P_S', 'L_ANKLE_P_S', 'L_ANKLE_R_S', 
                'R_HIP_P_S', 'R_HIP_R_S', 'R_HIP_Y_S', 'R_KNEE_P_S', 'R_ANKLE_P_S', 'R_ANKLE_R_S', 'WAIST_Y_S', 'WAIST_R_S', 'WAIST_P_S', 
                'L_SHOULDER_P_S', 'L_SHOULDER_R_S', 'L_SHOULDER_Y_S', 'L_ELBOW_Y_S', 'L_WRIST_P_S', 'L_WRIST_Y_S', 'L_WRIST_R_S', 
                'NECK_Y_S', 'R_SHOULDER_P_S', 'R_SHOULDER_R_S', 'R_SHOULDER_Y_S', 'R_ELBOW_Y_S', 'R_WRIST_P_S', 'R_WRIST_Y_S', 'R_WRIST_R_S']

  terminate_after_contacts_on : ["WAIST_P_S", "SHOULDER", "HIP"]
  penalize_contacts_on: ["WAIST_P_S",  "SHOULDER", "HIP"]
  init_state:
    pos: [0.0, 0.0, 0.8] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]

#  'L_HIP_Y', 'L_KNEE_P', 'L_ANKLE_P', 'L_ANKLE_R', 'R_HIP_P', 'R_HIP_R', 'R_HIP_Y', 'R_KNEE_P', 'R_ANKLE_P', 'R_ANKLE_R', 
#                 'WAIST_Y', 'WAIST_R', 'WAIST_P', 'L_SHOULDER_P', 'L_SHOULDER_R', 'L_SHOULDER_Y', 'L_ELBOW_Y', 'L_WRIST_P', 'L_WRIST_Y', 
#                 'L_WRIST_R', 'NECK_Y', 'R_SHOULDER_P', 'R_SHOULDER_R', 'R_SHOULDER_Y', 'R_ELBOW_Y', 'R_WRIST_P', 'R_WRIST_Y', 'R_WRIST_R']
    default_joint_angles: # = target angles [rad] when action = 0.0
      L_HIP_Y: 0.
      L_HIP_P: 0.
      L_HIP_R: 0.
      L_KNEE_P: 0.
      L_ANKLE_P: 0.
      L_ANKLE_R: 0.
      R_HIP_P: 0.
      R_HIP_R: 0.
      R_HIP_Y: 0.
      R_KNEE_P: 0.
      R_ANKLE_P: 0.
      R_ANKLE_R: 0.
      WAIST_Y: 0.
      WAIST_R: 0.
      WAIST_P : 0.
      L_SHOULDER_P : 0.
      L_SHOULDER_R : 0.
      L_SHOULDER_Y: 0.
      L_ELBOW_Y: 0.
      L_WRIST_P: 0.
      L_WRIST_Y: 0.
      L_WRIST_R: 0.
      NECK_Y: 0.
      R_SHOULDER_P: 0.
      R_SHOULDER_R: 0.
      R_SHOULDER_Y: 0.
      R_ELBOW_Y: 0.
      R_WRIST_P: 0.
      R_WRIST_Y: 0.
      R_WRIST_R: 0.



  randomize_link_body_names: [
    'WAIST_P_S', 'L_HIP_Y_S', 'L_HIP_R_S', 'L_HIP_P_S', 'L_KNEE_P_S',
    'R_HIP_Y_S', 'R_HIP_R_S', 'R_HIP_P_S', 'R_KNEE_P_S',
  ]

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      HIP_Y: 100
      HIP_R: 100
      HIP_P: 100
      KNEE_P: 200
      ANKLE_P: 20
      ANKLE_R: 20
      WAIST_Y: 400
      WAIST_R: 400
      WAIST_P: 400
      SHOULDER_P: 90
      SHOULDER_R: 60
      SHOULDER_Y: 20
      ELBOW_Y: 60
      WRIST_R: 20
      WRIST_P: 20
      WRIST_Y: 20
      NECK_Y: 20


    damping: # [N*m/rad]  # [N*m*s/rad]
      HIP_Y: 2.5
      HIP_R: 2.5
      HIP_P: 2.5
      KNEE_P: 5.0
      ANKLE_P: 0.2
      ANKLE_R: 0.1
      WAIST_Y: 5.0
      WAIST_R: 5.0
      WAIST_P: 5.0
      SHOULDER_P: 2.0
      SHOULDER_R: 1.0
      SHOULDER_Y: 0.4
      ELBOW_Y: 1.0
      WRIST_R: 0.4
      WRIST_P: 0.4
      WRIST_Y: 0.4
      NECK_Y: 0.4

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "tai5/${robot.asset.robot_type}.urdf"
    usd_file: "tai5/${robot.asset.robot_type}.usd"
    xml_file: "tai5/${robot.asset.robot_type}.xml"
    # xml_file: "g1/${robot.asset.robot_type}_fitmotionONLY.xml"
    robot_type: tai5
    self_collisions: 1 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

    fix_base_link: False # TEST: fix base link to world

  motion:
    motion_file : 'humanoidverse/data/motions/tai5/walk'
    # motion_file : 'humanoidverse/data/motions/g1_29dof/v1/singles/0-ACCAD_Male2General_c3d_A6- Box lift_poses.pkl'
    asset:
      assetRoot: "humanoidverse/data/robots/tai5/"
      # assetFileName: "g1_29dof_anneal_23dof.xml"
      assetFileName: "tai5.xml"
      urdfFileName: "tai5.urdf"

    isaac_gym_joint_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,23,24,25,26,27,28,29]
    use_joint_mapping: True
    sign_flip_set: {2,4,6,7,8,9} 

    # humanoid_type: g1_29dof_anneal_23dof
    bias_offset: False
    has_self_collision: True
    has_mesh: False
    has_jt_limit: False
    has_dof_subset: True
    has_upright_start: True
    has_smpl_pd_offset: False
    remove_toe: False # For humanoid's geom toe
    motion_sym_loss: False
    sym_loss_coef: 1
    big_ankle: True

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: False

    masterfoot: False
    freeze_toe: false
    freeze_hand: False
    box_body: True
    real_weight: True
    real_weight_porpotion_capsules: True
    real_weight_porpotion_boxes: True

    body_names: ['base_link', 'L_HIP_P_S', 'L_HIP_R_S', 'L_HIP_Y_S', 'L_KNEE_P_S', 'L_ANKLE_P_S', 'L_ANKLE_R_S', 
                 'R_HIP_P_S', 'R_HIP_R_S', 'R_HIP_Y_S', 'R_KNEE_P_S', 'R_ANKLE_P_S', 'R_ANKLE_R_S', 'WAIST_Y_S', 'WAIST_R_S', 'WAIST_P_S', 
                 'L_SHOULDER_P_S', 'L_SHOULDER_R_S', 'L_SHOULDER_Y_S', 'L_ELBOW_Y_S', 'L_WRIST_P_S', 'L_WRIST_Y_S', 'L_WRIST_R_S', 
                 'NECK_Y_S', 'R_SHOULDER_P_S', 'R_SHOULDER_R_S', 'R_SHOULDER_Y_S', 'R_ELBOW_Y_S', 'R_WRIST_P_S', 'R_WRIST_Y_S', 'R_WRIST_R_S']
          
    limb_weight_group: 
      - ['left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link']
      - ['right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link']
      - ['pelvis', 'waist_yaw_link', 'waist_roll_link', 'torso_link']
      - ['left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link']
      - ['right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link']

    dof_names: ['L_HIP_P', 'L_HIP_R', 'L_HIP_Y', 'L_KNEE_P', 'L_ANKLE_P', 'L_ANKLE_R', 'R_HIP_P', 'R_HIP_R', 'R_HIP_Y', 'R_KNEE_P', 'R_ANKLE_P', 'R_ANKLE_R', 
                 'WAIST_Y', 'WAIST_R', 'WAIST_P', 'L_SHOULDER_P', 'L_SHOULDER_R', 'L_SHOULDER_Y', 'L_ELBOW_Y', 'L_WRIST_P', 'L_WRIST_Y', 
                 'L_WRIST_R', 'NECK_Y', 'R_SHOULDER_P', 'R_SHOULDER_R', 'R_SHOULDER_Y', 'R_ELBOW_Y', 'R_WRIST_P', 'R_WRIST_Y', 'R_WRIST_R']
    right_foot_name: 'r_foot_roll'
    left_foot_name: 'l_foot_roll'


    nums_extend_bodies: 0
    extend_config: []

    motion_tracking_link: 
      - "L_ELBOW_Y_S"
      - "R_ELBOW_Y_S"
      - "NECK_Y_S"

    lower_body_link:
      - "WAIST_P_S"
      - "L_HIP_P_S"
      - "L_HIP_R_S"
      - "L_HIP_Y_S"
      - "L_KNEE_P_S"
      - "L_ANKLE_P_S"
      - "L_ANKLE_R_S"
      - "R_HIP_P_S"
      - "R_HIP_R_S"
      - "R_HIP_Y_S"
      - "R_KNEE_P_S"
      - "R_ANKLE_P_S"
      - "R_ANKLE_R_S"
      - "WAIST_Y_S"
      - "WAIST_R_S"

    # body_names: ['base_link', 'L_HIP_P_S', 'L_HIP_R_S', 'L_HIP_Y_S', 'L_KNEE_P_S', 'L_ANKLE_P_S', 'L_ANKLE_R_S', 
    #              'R_HIP_P_S', 'R_HIP_R_S', 'R_HIP_Y_S', 'R_KNEE_P_S', 'R_ANKLE_P_S', 'R_ANKLE_R_S', 'WAIST_Y_S', 'WAIST_R_S', 'WAIST_P_S', 
    #              'L_SHOULDER_P_S', 'L_SHOULDER_R_S', 'L_SHOULDER_Y_S', 'L_ELBOW_Y_S', 'L_WRIST_P_S', 'L_WRIST_Y_S', 'L_WRIST_R_S', 
    #              'NECK_Y_S', 'R_SHOULDER_P_S', 'R_SHOULDER_R_S', 'R_SHOULDER_Y_S', 'R_ELBOW_Y_S', 'R_WRIST_P_S', 'R_WRIST_Y_S', 'R_WRIST_R_S']

    upper_body_link:
      - "L_SHOULDER_P_S"
      - "L_SHOULDER_R_S"
      - "L_SHOULDER_Y_S"
      - "L_ELBOW_Y_S"
      - 'L_WRIST_P_S'
      - 'L_WRIST_Y_S'
      - 'L_WRIST_R_S'
      - "R_SHOULDER_P_S"
      - "R_SHOULDER_R_S"
      - "R_SHOULDER_Y_S"
      - "R_ELBOW_Y_S"
      - 'R_WRIST_P_S'
      - 'R_WRIST_Y_S'
      - 'R_WRIST_R_S'



    pelvis_link: "WAIST_P_S"
    base_link: "base_link"
    hips_link:
      - "L_HIP_P_S"
      - "L_HIP_R_S"
      - "L_HIP_Y_S"
      - "R_HIP_P_S"
      - "R_HIP_R_S"
      - "R_HIP_Y_S"
    
    joint_matches:
      - ["WAIST_P_S", "Pelvis"]
      - ["L_HIP_P_S", "L_Hip"]
      - ["left_knee_link", "L_Knee"]
      - ["left_ankle_roll_link", "L_Ankle"]
      - ["right_hip_pitch_link", "R_Hip"]
      - ["right_knee_link", "R_Knee"]
      - ["right_ankle_roll_link", "R_Ankle"]
      - ["left_shoulder_roll_link", "L_Shoulder"]
      - ["left_elbow_link", "L_Elbow"]
      - ["left_hand_link", "L_Hand"]
      - ["right_shoulder_roll_link", "R_Shoulder"]
      - ["right_elbow_link", "R_Elbow"]
      - ["right_hand_link", "R_Hand"]
      - ["head_link", "Head"]


    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"
      - L_Elbow: "[0, -np.pi/2, 0]"
      - R_Elbow: "[0, np.pi/2, 0]"

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0.929, 0.867, 0.437] # left_hip_yaw_joint
      - [0.929, 0.867, 0.437] # left_hip_yaw_joint
      - [0.929, 0.867, 0.437] # left_hip_roll_joint
      - [0.929, 0.867, 0.437] # left_hip_pitch_joint
      - [0.929, 0.867, 0.437] # left_knee_joint
      - [0.929, 0.867, 0.437] # left_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # left_ankle_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_yaw_joint
      - [0.929, 0.867, 0.437] # right_hip_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_pitch_joint
      - [0.929, 0.867, 0.437] # right_knee_joint
      - [0.929, 0.867, 0.437] # right_ankle_pitch_joint
      - [0.929, 0.867, 0.437] # right_ankle_roll_joint
      - [0.929, 0.867, 0.437] # waist_yaw_joint
      - [0.929, 0.867, 0.437] # waist_roll_joint
      - [0.929, 0.867, 0.437] # torso_joint (waist_pitch_link)
      - [0.929, 0.867, 0.437] # left_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # left_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # left_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # left_elbow_joint
      - [0.929, 0.867, 0.437] # right_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # right_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # right_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      # - [0.0, 1.0, 1.0] # right_elbow_joint

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1
